queue_rules:
  - name: hotfix
    queue_conditions:
      - label = hotfix
  - name: standard

pull_request_rules:
  - name: add lablel when author is rodo
    conditions:
      - author = rodo
    actions:
      label:
        add:
          - Rodolphe

  - name: put PRs in queue
    conditions:
      - and:
          - base=main
          - "#approved-reviews-by>=1"
    actions:
      queue:
